### ISSUE TITLE
Fix and improve CI/CD pipeline

### ISSUE THREAD

**Issue by kidk** [newrelic/infrastructure-agent-ansible#104]
User stories
* As a contributor I expect my code to be automatically reviewed by linting tools, and unit tests
* As a contributor I expect my code to be checked on the code standards that New Relic or Ansible requires
* As a contributor I expect my code to be checked against the operating systems that New Relic supports

**Comment by AnnaParot** [comment]
New pipeline was prepared. I'm closing the issue
