### ISSUE TITLE
Published on Ansible Galaxy?

### ISSUE THREAD

**Issue by jamescarr** [newrelic/infrastructure-agent-ansible#11]
I could not find this anywhere on ansible galaxy.

**Comment by chaupt** [comment]
@jamescarr At the moment, we are just here in GH in raw form. There are some PRs in progress to clean things up, and we are working on internal signoff regarding pushing things to the various repositories out there.

**Comment by chaupt** [comment]
We'll update the README and/or the doc when these become available on other repositories.
