### ISSUE TITLE
this code is broken now

### ISSUE THREAD

**Issue by nfplatzke** [newrelic/infrastructure-agent-ansible#114]
## Description
This commit: https://github.com/newrelic/infrastructure-agent-ansible/commit/bf8e76fcd6341c8080e13bddbb30ca5b2805d661

contains changes which are not valid ansible syntax.

Specifically, there are calls to the ansible file module that looks like this:

`- name: Ensure newrelic-infra.yml exists
  file:
    path: /etc/newrelic-infra.yml
    state: exists
    mode: 0600`

But "exists" is not a valid state for the ansible file module. 

## Expected Behavior
I would expect this code to be tested before it is released.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
literally just run the code

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by JakubKotkowiak** [comment]
Hello @nfplatzke, thanks for catching it. It will be resolved in one of the PRs that are waiting for approval. Have a nice day
