### ISSUE TITLE
Missing when clause for the following instruction: confirm redhat lsb util is present pre2.8.0

### ISSUE THREAD

**Issue by JakubKotkowiak** [newrelic/infrastructure-agent-ansible#119]
## Description
In the when clause for 
- name: confirm redhat lsb util is present pre2.8.0
there's no ensurance that the version of ansible being used is lower than 2.8.0 and it's causing issues.

## Expected Behavior
This instruction isn't used when running ansible version higher than 2.8.0

## Your Environment
Ansible 2.9.0
Ubuntu 20.04

**Comment by nordri** [comment]
Yes! this is what i was saying in the PR conversation!
Thanks a lot!
