### ISSUE TITLE
How do I install this role?

### ISSUE THREAD

**Issue by tadas-subonis** [newrelic/infrastructure-agent-ansible#13]
It appears that it is not on the Galaxy. How do I install it?

**Comment by tedder** [comment]
Sources don't have to exist on Galaxy to be installable with it:

    ansible-galaxy install -p roles/ git+https://github.com/newrelic/infrastructure-agent-ansible

As an alternative, it can be installed with `git submodule`. Note I prefer a role name that makes more sense:

    git submodule add https://github.com/newrelic/infrastructure-agent-ansible roles/newrelic_infrastructure_agent
