### ISSUE TITLE
Error when installing as a user other than 'root'

### ISSUE THREAD

**Issue by danteata** [newrelic/infrastructure-agent-ansible#15]
I'm using another user (which is also a sudoer) to run the playbook. When it gets to the step; 
`TASK [nrinfragent : setup agent repo keys]`

the run fails with:

`This command can only be used by root.`

**Comment by smith** [comment]
We require a root user to install the agent (see https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/getting-started/compatibility-requirements-new-relic-infrastructure#permissions). Having the repo add the keys will also require root, which sounds like what you're seeing.

Closing this, but please reopen if I'm misunderstanding. Thanks!
