### ISSUE TITLE
Configuration nrinfragent_logging not working

### ISSUE THREAD

**Issue by ngandara-summa** [newrelic/infrastructure-agent-ansible#151]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

Configuration nrinfragent_logging not working.

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

The nrinfragent_logging configuration does not work. Checking the commit (https://github.com/newrelic/infrastructure-agent-ansible/commit/88d7172ff8abbcbbe61d81fae4fec1cba522cc00) and the files of the last TAG, and master, I do not see that the setup_logging.yml task is imported. Is it a functionality that is not finished yet? If so, do you know when it will be ready? Thanks! 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

After configure nrinfragent_logging and run ansible i not see in the directory /etc/newrelic-infra/logging.d with my customizations.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

The role is configured as in the example https://github.com/newrelic/infrastructure-agent-ansible/blob/master/defaults/main.yml

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

...

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

Amazon Linux 2

**Comment by cici709394** [comment]
Any ETA of a finalized logging configuration task in this Ansible role ? BTW, I would greatly appreciate if the WIP or TBC status is mentioned somewhere in the README.md, so that we don't have to waste time in meaningless troubleshooting.

**Comment by cacostanofraud** [comment]
Got the same issue trying to use the nrinfragent_logging configuration.

**Comment by cschlesselmann** [comment]
Just stumbled across this issue as well. Would love to see this functionality finished.

And imo there should be a big warning in the docs that this isn't working yet.
