### ISSUE TITLE
Please publish an updated release on Galaxy

### ISSUE THREAD

**Issue by RulerOf** [newrelic/infrastructure-agent-ansible#161]
I wasted over an hour duplicating the patch from #156, which was merged over 3 months ago, because the release in Galaxy is so old.

**Comment by josemore** [comment]
Hi @RulerOf, thanks for pointing this out, we'll look into publishing an update on Galaxy.

**Comment by RulerOf** [comment]
Thanks @josemore. My apologies for my tone in the request. It was late and I was cranky :P
