### ISSUE TITLE
Support Ansible Core 2.11

### ISSUE THREAD

**Issue by josemore** [newrelic/infrastructure-agent-ansible#162]
Ansible Core 2.9 will be going end of life in December 2022.
Required to test our artifacts against 2.11. [Guideline here](https://connect.redhat.com/blog/testing-content-collections-ansible-automation-platform-20).

**Comment by richyta** [comment]
Does this work now with ansible core 2.11?

**Comment by josemore** [comment]
This issue is open to validate with core 2.11.

**Comment by rogercoll** [comment]
Related issue: https://github.com/newrelic/newrelic-agents-ansible-collection/issues/2
