### ISSUE TITLE
Stop testing deprecated operating systems

### ISSUE THREAD

**Issue by RulerOf** [newrelic/infrastructure-agent-ansible#166]
## Is your feature request related to a problem? Please describe.
CentOS 8 and Ubuntu 16.04 are EOL. Forward testing against them doesn't make sense and complicates adding new features.

## Feature Description
- Remove CentOS 8
- Remove Ubuntu 16.04
- Add a suitable EL8 replacement (Oracle/Rocky/Alma/etc)

## Describe Alternatives
Broken tests 😁

## Additional context
Opening this issue to correspond to a PR I've already prepared.

## Priority
Blocker

**Comment by rogercoll** [comment]
Hi @RulerOf , thanks for the contributions in https://github.com/newrelic/infrastructure-agent-ansible/pull/167
Although CentosOS 8 and Ubuntu 16.04 are EOL, we are still generating/testing the infra-agent packages for these distributions. We wait some more months after an EOL in case a customer is still migrating its hosts.

You can find the current supported distributions here: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent#operating-systems

Rocky linux is still not officially supported. Could you provide more details on the "Broken tests" part?

**Comment by RulerOf** [comment]
Okay. I'll re-add CentOS 8 to my patch and report anything I can reproduce. Should be able to get this closed out promptly. Thanks @rogercoll!

**Comment by RulerOf** [comment]
@rogercoll please review and merge #167 at your convenience. Its merge should automatically resolve this issue.

Thanks again!
