### ISSUE TITLE
how to use log_file option for windows and linux?

### ISSUE THREAD

**Issue by Hokwang** [newrelic/infrastructure-agent-ansible#173]
## Description
I want to install both linux and windows server. 
In this case, how to seperate `log_file` option under `nrinfragent_config:` ?

when if I write linux path, below step failed in windows OS.
https://github.com/newrelic/infrastructure-agent-ansible/blob/f993fe46bb3a4c5fded3ec35befbe9c9acf2eb19/tasks/install_dist_pkgs.yml#L95-L102

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
