### ISSUE TITLE
Agent installation fails with missing ansible_lsb dictionary on Debian bullseye

### ISSUE THREAD

**Issue by roehrijn** [newrelic/infrastructure-agent-ansible#191]
I'm trying to install the agent on a Proxmox-VE machine which is based on Debian `bullseye`.

The ansible run fails with:

        TASK [newrelic.newrelic-infra : setup agent repo reference] *************************************************************************************************************************
        fatal: [hv01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ ansible_lsb.codename }}: 'dict object' has no attribute 'codename'\n\nThe error appears to be in '/home/****/.ansible/roles/newrelic.newrelic-infra/tasks/install_dist_pkgs.yml': line 45, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: setup agent repo reference\n  ^ here\n"}

This is because Proxmox VE has package `lsb-release` not installed by default and thus the `ansible_lsb` dictionary is empty.

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
