### ISSUE TITLE
Need Guidance/Help

### ISSUE THREAD

**Issue by DanaEckart** [newrelic/infrastructure-agent-ansible#193]
Using the "simple" playbook with defaults seems to look for tarball information rather than finding appropriate files for AWS Amazon Linux. Playbook ends up failing. Just trying to get something basic working for infra agent installs.

I've attached the playbook and hosts files.

[hosts_test.txt](https://github.com/newrelic/infrastructure-agent-ansible/files/9804713/hosts_test.txt)
[NRPlaybook_test.yml.txt](https://github.com/newrelic/infrastructure-agent-ansible/files/9804714/NRPlaybook_test.yml.txt)

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
