### ISSUE TITLE
Unable to set http_proxy environment variable

### ISSUE THREAD

**Issue by bathas2021** [newrelic/infrastructure-agent-ansible#199]
### Description
It won't allow to download the new relic infra agent though a proxy server

### Acceptance Criteria
Trying to configure the infra gent on multiple remote server but its not able to download the binaries from the repo through proxy server.
Error: FAILED! => {"changed": false, "dest": "/opt/newrelic//newrelic-infra_linux_1.33.0_amd64.tar.gz", "elapsed": 40, "msg": "Request failed: <urlopen error timed out>", "url": "http://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/newrelic-infra_linux_1.33.0_amd64.tar.gz"}

### Design Consideration/Limitations
Issue is the yaml is not correctly setting the http_proxy env variable in the remote machine.

### Additional context
Ansible playbook with
---
- hosts: servers
  become: yes
  roles:
    - role: newrelic.newrelic-infra
      vars:
        nrinfragent_tarball_version: 1.33.0
        nrinfragent_tarball_download_dir: /opt/newrelic/
        nrinfragent_config:
          log_file: /opt/logs/newrelic-infra.log
          verbose: 0
          license_key: XXXXXXXX
          proxy: https://X.X.X.X:8888
      custom_attributes:
        environment: dev
### Estimates
_Please provide initial t-shirt size. S = 1-3 days,  M = 3-5 days (1 week), L = 1-2 weeks (1 sprint)_

**Comment by josemore** [comment]
consider using https://github.com/newrelic/ansible-install going forward
