### ISSUE TITLE
Warning when updating apt cache after install

### ISSUE THREAD

**Issue by cwjackso** [newrelic/infrastructure-agent-ansible#203]
## Description
When installing on Ubuntu 22.04 a GPG key warning occurs due to the use of the deprecated GPG key method. Ansible have a recommended new approach see : https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html

## Expected Behavior
No warning is generated rather than the below 

`Failed to update apt cache: W:https://download.newrelic.com/infrastructure_agent/linux/apt/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
`

**Comment by davidgit** [comment]
Hi @cwjackso,

After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. 

We will try to prioritize this issue asap.
