### ISSUE TITLE
ERROR! couldn't resolve module/action 'zypper_repository' (Fedora)

### ISSUE THREAD

**Issue by mariusa** [newrelic/infrastructure-agent-ansible#206]
Hi,

## Description

Trying to install newrelic on Fedora 37 with this ansible .yml file:

```
---
- hosts: localhost
  become: yes
  gather_facts: yes
  roles:
    - role: newrelic.newrelic-infra
      vars:
        nrinfragent_config:
          license_key: REDACTED
          nrinfragent_state: latest
          enable_process_metrics: true
```

Result
```
# ansible-playbook newrelic.yml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'zypper_repository'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/.ansible/roles/newrelic.newrelic-infra/tasks/install_dist_pkgs.yml': line 76, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: setup agent repo reference
  ^ here
```

Already done:
```
ansible-galaxy install newrelic.newrelic-infra
```

## Expected Behavior
Install NR and have the config changed to include process monitors.

## Your Environment
Fedora 37

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by davidgit** [comment]
Hi @mariusa 

I don't have a solution for you for this role, but we're building a new role. You can find the details here: https://github.com/newrelic/ansible-install

Would love to hear your thoughts.

Thanks

**Comment by mariusa** [comment]
Thanks David, tried that and found https://github.com/newrelic/ansible-install/issues/40
