### ISSUE TITLE
Red Hat 9 distros have retired needed redhat-lsb-core package

### ISSUE THREAD

**Issue by msncookie** [newrelic/infrastructure-agent-ansible#209]
## Description
We are attempting to use the infrastructure-agent-ansible role on Red Hat Enterprise Linux 9 and CentOS Stream 9 and are running into an issue where `tasks/install_dist_pkgs.yml` is trying to install the `redhat-lsb-core` package via `yum`, which no longer exists in these distros.  Need to find another way to query OS information.

## Steps to Reproduce
Run the role on any Red Hat 9 variant.  Yum will error-out on an unknown package `redhat-lsb-core`

## Your Environment
Tested on RHEL 9 and CentOS 9

## Additional context
See `tasks/install_dist_pkgs.yml`.  The first few tasks are related to lsb installation and fact gathering.  We were able to work around the issue temporarily by commenting-out these tasks and hard-coding the OS related variables to redhat 9.  This allows the package download to complete successfully.

**Comment by josemore** [comment]
Thanks for reporting this. 
Quick note: a different Ansible role is being developed: https://github.com/newrelic/ansible-install

This would replace the infra-specific role in the future, it'd be great if you can try it and provide feedback there.

**Comment by msncookie** [comment]
@josemore Thanks for the quick reply.  Will check it out.
