### ISSUE TITLE
Not compatible with RHEL 9

### ISSUE THREAD

**Issue by lisenet** [newrelic/infrastructure-agent-ansible#210]
## Description

Ansible role does not work with RHEL 9 as it depends on ` redhat-lsb-core`.

Currently Red Hat has no plan to make `redhat-lsb-core` available in RHEL 9 as this package is not satisfying some of dependencies in RHEL 9. Customers are encouraged to set their applications to use the fields in `/etc/os-release` file instead.

## Expected Behavior

It would be nice to make this role compatible with RHEL 9.

## Troubleshooting results
```bash
fatal: [10.11.22.33]: FAILED! => changed=false 
  failures:
  - No package redhat-lsb-core available.
  msg: Failed to install some of the specified packages
  rc: 1
  results: []
```

**Comment by josemore** [comment]
thanks for submitting this, we'll consider this in https://github.com/newrelic/ansible-install going forward.
