### ISSUE TITLE
license key var should be unique

### ISSUE THREAD

**Issue by jloh** [newrelic/infrastructure-agent-ansible#3]
The var `license_key` should be more unique to this role to avoid conflics and make it a buttload more obvious what it even means.

Something like `newrelic_license_key` makes a lot more sense!

**Comment by chaupt** [comment]
Thank you for the suggestion. We'll take a look on the next pass.

**Comment by chaupt** [comment]
Fixed in #5 which is now merged. Also documented in README.md
