### ISSUE TITLE
Install in AWS error

### ISSUE THREAD

**Issue by ManriqueGarcia** [newrelic/infrastructure-agent-ansible#31]
When we tried to install we have this error
---------------------

TASK [newrelic_infrastructure_agent : install agent] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "msg": "https://download.newrelic.com/infrastructure_agent/linux/yum/el/2017/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found\nTrying other mirror.\nTo address this issue please refer to the below knowledge base article \n\nhttps://access.redhat.com/articles/1320623\n\nIf above article doesn't help to resolve this issue please open a ticket with Red Hat Support.\n\nhttps://download.newrelic.com/infrastructure_agent/linux/yum/el/2017/x86_64/newrelic-infra-1.0.859-1.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found\nTrying other mirror.\nhttps://download.newrelic.com/infrastructure_agent/linux/yum/el/2017/x86_64/newrelic-infra-integrations-1.3.0-1.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found\nTrying other mirror.\n\n\nError downloading packages:\n newrelic-infra-integrations-1.3.0-1.x86_64: [Errno 256] No more mirrors to try.\n newrelic-infra-1.0.859-1.x86_64: [Errno 256] No more mirrors to try.\n\n", "rc": 1, "results": ["Loaded plugins: priorities, update-motd, upgrade-helper\n1034 packages excluded due to repository priority protections\nPackage newrelic-infra-integrations-beta is obsoleted by newrelic-infra-integrations, trying to install newrelic-infra-integrations-1.3.0-1.x86_64 instead\nResolving Dependencies\n--> Running transaction check\n---> Package newrelic-infra.x86_64 0:1.0.859-1 will be installed\n---> Package newrelic-infra-integrations.x86_64 0:1.3.0-1 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package Arch Version Repository Size\n================================================================================\nInstalling:\n newrelic-infra x86_64 1.0.859-1 New-Relic-Infrastructure 5.9 M\n newrelic-infra-integrations x86_64 1.3.0-1 New-Relic-Infrastructure 9.0 M\n\nTransaction Summary\n================================================================================\nInstall 2 Packages\n\nTotal download size: 15 M\nInstalled size: 44 M\nDownloading packages:\n"]}
to retry, use: --limit @/etc/ansible/installnewrelic.retry

My playbook is
----
- hosts: localhost
connection: local
roles:
- name: newrelic_infrastructure_agent
vars:
nrinfragent_config:
nrinfragent_os_name: Amazon
nrinfragent_os_version: “2017.9”
license_key: xxxxxxxxxxxxxxxxxxxxxx
log_file: /var/log/newrelic/nr-infra.log
log_to_stdout: false

[root@ip-17cxxx ~]# uname -a
Linux ip-xxx 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[root@ip-17xxx2 ~]# lsb_release -a
LSB Version: :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: AmazonAMI
Description: Amazon Linux AMI release 2017.9
Release: 2017.9
Codename: n/a

Although I change vars the result is the same
-----

nrinfragent_os_name: redhat
nrinfragent_os_version: 6

Thanks , best regards

**Comment by xino12** [comment]
Hi @ManriqueGarcia 
It seems there is a problem of how the url is being generated.

This is the correct URL, as you can see there is a 7 whereas in your url there is a 2017.
`https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/newrelic-infra-integrations-1.3.0-1.x86_64.rpm`
Your url:
`https://download.newrelic.com/infrastructure_agent/linux/yum/el/2017/x86_64/newrelic-infra-integrations-1.3.0-1.x86_64.rpm`

You should change your var:

`nrinfragent_os_version: “2017.9”`

To:
`nrinfragent_os_version: “7”`

Hope this helps.

**Comment by ManriqueGarcia** [comment]
Thanks, 

Yes, If I changed var runs well but I need a massive installation in several servers and the nrifnragent_os_version is

nrinfragent_os_version:  "{{ ansible_lsb.major_release }}"

Then major release is 2017. How can I form the URL when th Major release is for AWS AMI?

Thanks

**Comment by xino12** [comment]
I'd suggest you leverage group_vars functionality that ansible has and configure them using that.
http://docs.ansible.com/ansible/latest/intro_inventory.html#splitting-out-vars

And modify the vars file accordingly.

Hope this helps.

**Comment by ManriqueGarcia** [comment]
Thanks, Finally I make a fact

- name: set repo verison
 set_fact:
   nrinfragent_repo_version: 6
   when: nrinfragent_os_version == 2017

Regards
