### ISSUE TITLE
 "No package(s) matching 'newrelic-infra*' available"

### ISSUE THREAD

**Issue by Asshad** [newrelic/infrastructure-agent-ansible#34]
Hi. I was trying to install newrelic-infra agent and this error came out. Could you please advice?
The full traceback is:

os_name: Debian
os_version: jessie

  File "/tmp/ansible_nXwopM/ansible_module_apt.py", line 434, in expand_pkgspec_from_fnmatches
    pkg_name_cache = _non_multiarch

fatal: [vid-si.support-ml.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "name": "newrelic-infra*",
            "only_upgrade": false,
            "package": [
                "newrelic-infra*"
            ],
            "purge": false,
            "state": "latest",
            "update_cache": null,
            "upgrade": null
        }
    },
    "msg": "No package(s) matching 'newrelic-infra*' available"
}

**Comment by xino12** [comment]
Hi @Asshad , have made any modification to the role?
I've just tried it myself and it's working. Maybe it was a small network interruption with the repo?

Hope this helps

**Comment by Asshad** [comment]
Hi Ruben @xino12  , no I didn't do any modification.
I've tried it myself as well, let say I have 10 instances, running the same Debian version, some succeed, and some failed. 

Btw, the error came out when I was running on -C flag.

**Comment by xino12** [comment]
That's because the repo information when running in check mode does not get updated. That's why it can't find the package.

**Comment by Asshad** [comment]
@xino12 Great. It works! Thanks a bunch!
