### ISSUE TITLE
Error on Amazon linux

### ISSUE THREAD

**Issue by emersonmoura** [newrelic/infrastructure-agent-ansible#35]
Error:
![image](https://user-images.githubusercontent.com/5419868/37871649-5e15519e-2fc9-11e8-9889-23536f35e740.png)

On Ansible:
![image](https://user-images.githubusercontent.com/5419868/37871655-82b79ed0-2fc9-11e8-92b9-f88194a150c8.png)

Is creating the wrong path
https://download.newrelic.com/infrastructure_agent/linux/yum/el/2016/x86_64/repodata/repomd.xml

should not it be?
https://download.newrelic.com/infrastructure_agent/linux/yum/el/6/x86_64/repodata/repomd.xml

**Comment by smith** [comment]
@emersonmoura thanks for reporting this. As a workaround, can you try setting `nrinfragent_os_version` to `6`?

**Comment by emersonmoura** [comment]
@smith 
Yes, it was the first thing I tried, but the result was the same

**Comment by xino12** [comment]
Hey @emersonmoura so as a workaround you can check this issue: https://github.com/newrelic/infrastructure-agent-ansible/issues/31

**Comment by emersonmoura** [comment]
Tranks @smith 
helped to better understand

All the attempts to define the variable in my context did not work out, so I defined it directly from the role:

/roles/newrelic.newrelic-infra/vars/main.yml

![image](https://user-images.githubusercontent.com/5419868/37937348-a742ac24-312f-11e8-8d2e-9d92d2652afa.png)

That's works. Any ideas in the right way?

**Comment by emersonmoura** [comment]
no variable is setting the value. Now does not set the license key...

**Comment by xino12** [comment]
Hello @emersonmoura, have you checked https://github.com/newrelic/infrastructure-agent-ansible/blob/master/templates/newrelic-infra.yml.j2

The templates needs nrinfragent_license_key variable in order to create a proper newrelic-infra configuration file so it can start properly.

Hope this helps.

**Comment by emersonmoura** [comment]
Hi @xino12 
I did the test before posting the error here
I had already analyzed the source ...
Even so, it does not define the license value

**Comment by smith** [comment]
@emersonmoura could you please try the branch on #37 to see if it fixes it for you?

**Comment by smith** [comment]
This should be fixed in 0.3.1.

**Comment by emersonmoura** [comment]
@smith I'm sorry for the late reply
 
after upgrading to version 0.3.1 now it installs the service, but can not find

![image](https://user-images.githubusercontent.com/5419868/39078460-f07a9e5a-44e0-11e8-852d-b56d945fa03a.png)

follows the config:

![image](https://user-images.githubusercontent.com/5419868/39078476-10c4309a-44e1-11e8-857e-195170f20b15.png)

**Comment by smith** [comment]
@emersonmoura could you please open a separate issue for this?
