### ISSUE TITLE
Installing via ansible-galaxy fails with error "Role has no field named u'owner'"

### ISSUE THREAD

**Issue by mlandauer** [newrelic/infrastructure-agent-ansible#39]
```
$ ansible-galaxy install newrelic/newrelic-infra
- downloading role 'newrelic/newrelic-infra', owned by
 [WARNING]: - newrelic/newrelic-infra was NOT installed successfully: Role has no field named u'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by mlandauer** [comment]
Just for reference, I have no trouble installing other things from ansible-galaxy in exactly the same way

**Comment by smith** [comment]
According to the docs you should be using `newrelic.newrelic-infra`: https://galaxy.ansible.com/intro

Not sure why other roles work as you described, but I was able to install this one with the dot. Please reopen if that doesn't work for you.
