### ISSUE TITLE
Wrong Amazon repo.

### ISSUE THREAD

**Issue by dmartsynkevych** [newrelic/infrastructure-agent-ansible#42]
Got error:
...
TASK [infrastructure-agent-ansible : setup agent service] 
fatal: [10.252.151.150]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service newrelic-infra: host"}

REASON:
/etc/yum.repos.d/New-Relic-Infrastructure.repo contains repo for RedHat7:
baseurl = https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64
but Amazon instances does not have systemd and can't use 
/etc/systemd/system/newrelic-infra.service

As temporary solution I've changed one line in file infrastructure-agent-ansible/tasks/main.yml

    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ (ansible_distribution == 'Amazon') | ternary('7', nrinfragent_os_version) }}/x86_64"
to

    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ (ansible_distribution == 'Amazon') | ternary('6', nrinfragent_os_version) }}/x86_64"

There also no /etc/init.d/newrelic-infra script in RedHat6 package, so problem with service auto start still exists.

**Comment by zxaos** [comment]
@smith this change actually _introduces_ the issue on Amazon Linux 2, which does use systemd. This issue should be re-opened.

**Comment by alejandrodnm** [comment]
We'll investigate this. Thanks @zxaos for reporting the issue with Amazon Linux 2

**Comment by mirandapearson** [comment]
Reproduced the issue on Amazon Linux 2, as well.

**Comment by cristianciutea** [comment]
This has been fixed by #59 
We will release this as version 0.6.1 today.
