### ISSUE TITLE
Update docs: specify exact name of role in Galaxy 

### ISSUE THREAD

**Issue by hodnett** [newrelic/infrastructure-agent-ansible#44]
When searching for "nrinfragent" in Ansible Galaxy, Galaxy will return zero matches.

When searching for "infrastructure-agent-ansible" in Galaxy, the following entries are returned: EclecticIQ.infrastructure-agent-ansible and buluma.infrastructure-agent-ansible. Both of these are likely to be forks of this Github project. It would be up to the end-user to review those repositories and confirm that there are no key-loggers or similar malicious additions.

When searching for all Ansible roles authored by "newrelic", it returns one match, newrelic-infra. Since New Relic has apparently authored only one role to date, the end-user cannot assume that the authorship field hasn't been spoofed. (In other words, there's nothing really preventing me from creating a "new-relic" account and pretending to be the official account.)

It's only by comparing the project linked to in that role with the this Github repo, that I'm reasonably confident that I've found the right role. Keep in mind that the [New Relic Documentation](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/config-management-tools/configure-new-relic-infrastructure-using-ansible)'s examples do **not** match the README.md text here. They suggest setting nrinfragent_os_name in their example, you do not.

Potential Quick Fixes:

- Explicitly state the full name of the Ansible role (newrelic.newrelic-infra) within the New Relic Documentation and/or within this README.md file.

- Link to the correct project page in Ansible Galaxy, likewise in the docs or the readme.

- Rename the role within the examples in the documentation and readme from nrinfragent to newrelic-infra.

- Publicly state that none of these roles are authorized, and encourage people to clone this github project directly.

**Comment by smith** [comment]
@hodnett thanks so much for this input. We can probably take care of most of it. I had a couple questions:

> Link to the correct project page in Ansible Galaxy, likewise in the docs or the readme.

Could you clarify what you mean here? The Issue Tracker and GitHub Repo links on the Ansible Galaxy page (https://galaxy.ansible.com/newrelic/newrelic-infra/) go here, and the link in our docs goes to that Ansible Galaxy page. 

> Publicly state that none of these roles are authorized, and encourage people to clone this github project directly.

What do you mean by this? The role on this repo which is hosted on Ansible Galaxy are supported. Do you need us to state somewhere that forks of this role or other roles on Galaxy are not supported by us?

**Comment by smith** [comment]
#47 should take care of the README. I've submitted a change to the docs to make the naming clearer. Please let us know if there's any more changes you would find helpful.

**Comment by hodnett** [comment]
Thank you.

**It's moot now** but to answer the original questions asked: the links in the New Relic documentation originally led here, not to Ansible Galaxy role page. I should have also been more clear. If you did not intend for us to search for or follow links to Ansible Galaxy with the implication being that none of the roles in Galaxy are sanctioned, and you wanted us to instead clone this repo, then there should have been a note here to that effect.
