### ISSUE TITLE
Unable to parse configuration file

### ISSUE THREAD

**Issue by nderzhak** [newrelic/infrastructure-agent-ansible#45]
The book generates wrong config.

There is {} in defaults/main.yml 
```
nrinfragent_config: {}
```
And it goes to config in template: 
```
templates/newrelic-infra.yml.j2
```
What was initial intention here ?

I understand I can set nrinfragent_config to empty string. But then why no to make it default ?

```
May 11 18:18:47 localhost newrelic-infra: time="2018-05-11T18:18:47Z" level=fatal msg="can't load configuration file" error="Unable to parse configuration file : yaml: line 3: could not find expected ':'" 
May 11 18:18:47 localhost kernel: [63650758.301253] init: newrelic-infra main process (544476) terminated with status 1
```

```
cat /etc/newrelic-infra.yml
license_key: 2f6898e65980897ecd733238b5ce1b397ef7b291

{}
```

**Comment by nderzhak** [comment]
https://github.com/newrelic/infrastructure-agent-ansible/commit/e45e1f87e01e0581df4d2eefb2937c6b5f5c243f

**Comment by nderzhak** [comment]
Well It seems I cook it old way . And I need to use that new variable you introduced:
```
nrinfragent_config:
          license_key: YOUR_LICENSE_KEY
          log_file: /var/log/newrelic/nr-infra.log
          log_to_stdout: false
``

Please confirm

**Comment by smith** [comment]
@nderzhak yes you're correct. #46 sets a default and should have a clearer failure. Thanks!
