### ISSUE TITLE
Support for ubuntu 18.04 LTS (bionic beaver)

### ISSUE THREAD

**Issue by omega** [newrelic/infrastructure-agent-ansible#52]
There is no such release in the apt repo at the moment, so it dies out while setting up. I don't know if there are any plans for a release for 18.04, but if there is it would be good if this role also supported it :+1:

**Comment by alejandrodnm** [comment]
Hi @omega we have in our roamap to add support for Ubuntu 18.04 and refactor this repo (we know it needs some love), in the meantime you can try changing this line:

https://github.com/newrelic/infrastructure-agent-ansible/blob/344c16d4d94ed6c850604ff0687712137f95a149/tasks/main.yml#L36

Replace `{{ nrinfragent_os_codename }}` with `xenial`

**Comment by omega** [comment]
I managed to do that from the outside by setting it outside the `vars`, so I am using those packages now, thanks for the suggestions 👍

**Comment by alejandrodnm** [comment]
Hi @omega we release the bionic version and the bioninc repo, it should work now with the default options.
