### ISSUE TITLE
Version 0.6.0 not available on Galaxy 

### ISSUE THREAD

**Issue by gmsantos** [newrelic/infrastructure-agent-ansible#57]
The latest release (0.6.0) is not published to Ansible Galaxy yet

https://galaxy.ansible.com/newrelic/newrelic-infra

![image](https://user-images.githubusercontent.com/1991286/49036808-cc087300-f19f-11e8-858a-5f2240f08de8.png)

I think the release need to be imported on Galaxy, idk for sure how this process works.

**Comment by xino12** [comment]
Thanks @gmsantos ! we've fixed this situation.

**Comment by gmsantos** [comment]
Thanks @xino12
