### ISSUE TITLE
nrinfragent_version requires preceding "=" sign

### ISSUE THREAD

**Issue by mlupton-st** [newrelic/infrastructure-agent-ansible#58]
When setting the `nrinfragent_version` in an ansible role, a preceding equals sign is required, otherwise you'll receive the following during playbook execution. 

`fatal: [your ip]: FAILED! => {"changed": false, "msg": "No package matching 'newrelic-infra1.1.4' is available"}`

Doing this resolves it `nrinfragent_version: "=1.1.4"`

**Comment by alejandrodnm** [comment]
Hi @mlupton-st thanks for reporting this, we'll take a look

**Comment by mariomac** [comment]
Hi @mlupton-st, let me close this issue, since we have removed the `nrinfragent_version` property and this issue does not apply anymore.

Now, only `nrinfragent_state: latest` is possible.
