### ISSUE TITLE
Install without starting the service

### ISSUE THREAD

**Issue by radykal-com** [newrelic/infrastructure-agent-ansible#60]
When using ansible to bake images (for example with packer), I would like to have the option to install the agent during the bake process but don't start the agent, just set the state as enabled so the final instance running the image will start it, but it won't be running during the initial image creation.

If you want I could just submit the PR with the change

**Comment by xino12** [comment]
That's a very interesting use case.

Yes please submit a PR and we will review it ASAP.
Please make it configurable in a variable so we don't change the behaviour by default.

Thanks

**Comment by xino12** [comment]
closed by https://github.com/newrelic/infrastructure-agent-ansible/pull/61
