### ISSUE TITLE
Support lock_timeout

### ISSUE THREAD

**Issue by scottelundgren** [newrelic/infrastructure-agent-ansible#71]
I'm using Amazon Linux 2 (4.14.123-111.109.amzn2.x86_64) with python (v2.7.14) that has installed Ansible (v2.8.1) via pip. Packer (v1.4.1) builds of AMI's thru ansible_local fail with
```
amazon-ebs: TASK [roles/newrelic.newrelic-infra : install agent] ***************************
amazon-ebs: fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "yum lockfile is held by another process"}
``` 
Ansible 2.8 introduced more complex handing in the yum module where lock_timeout is the number of seconds to wait for the yum lock before giving up and exiting. The default is 0 seconds but can be overridden at the task and module level. The package module has no support for this concept. Thus trying to apply the New Relic agent onto yum based distro's using Ansible 2.8 AMI's fails.

**Comment by alejandrodnm** [comment]
Hi @scottelundgren thanks for raising the issue, we will try to view this as soon as possible.

**Comment by nordri** [comment]
Hi!
Any update on this?
