### ISSUE TITLE
Version 0.8.2 not available on Ansible Galaxy

### ISSUE THREAD

**Issue by ripclawffb** [newrelic/infrastructure-agent-ansible#76]
The latest release of this role is not available on Ansible Galaxy.

https://galaxy.ansible.com/newrelic/newrelic-infra

Can you please publish it? Thanks!

**Comment by ripclawffb** [comment]
@alejandrodnm @varas @matiasburni @mariomac would one of you be able to publish this on Ansible Galaxy?

**Comment by alejandrodnm** [comment]
Hi @ripclawffb, I no longer work on the team that maintains this, but I'll let them know. Cheers.

**Comment by davidbrota** [comment]
Hi @ripclawffb, version 0.8.2 is already available. Sorry for the delay. Good Luck!
