### ISSUE TITLE
Add support for Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by laynegeck** [newrelic/infrastructure-agent-ansible#83]
There is no corresponding release in the apt repo yet, so it doesn't work.

**Comment by josemore** [comment]
Thanks for submitting the issue @laynegeck, better support for Ubuntu 20 is currently in our plan so we'll share the update here when ready.

**Comment by scottanderson42** [comment]
This is an unfortunate discovery. We're upgrading to 20.04 and just discovered that the NewRelic "infrastructure-agent-ansible" fails. Can we get a timeline on this support?

**Comment by piwan** [comment]
Workaround (I hope not for long): 
```
- name: newrelic.newrelic-infra
  nrinfragent_os_codename: bionic
```
(i.e. install it from Ubuntu 18 repository)

**Comment by prateekvarma** [comment]
Any updates on this? Thanks!

**Comment by alechko** [comment]
We've just upgraded servers to 20.04 and discovered that there's no new relic support. 

> Workaround (I hope not for long):
> 
> ```
> - name: newrelic.newrelic-infra
>   nrinfragent_os_codename: bionic
> ```
> 
> (i.e. install it from Ubuntu 18 repository)

This workaround did not work, we're getting `FAILED! => {"changed": false, "msg": "No package matching 'newrelic-infra' is available"}` error either way.

There's no going back with our infrastructure update and we have lost our insight, is there any eta for this issue?

**Comment by josemore** [comment]
Support for Ubuntu 20 (focal packages) was recently added in the infrastructure agent and on-host integrations: [https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent).

**Comment by glauberferreira** [comment]
> Support for Ubuntu 20 (focal packages) was recently added in the infrastructure agent and on-host integrations: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.

@josemore I am getting the same error from @alechko : `"No package matching 'newrelic-infra' is available"` when I use `nrinfragent_os_version: fossa`.

It seems that New Relic Infrastructure Agent supports Ubuntu 20 since version 1.13.2 (19 Nov 2020). But, the latest version of Ansible role for the New Relic infrastructure agent is 0.8.2 and has been released more than one year ago (10 Jul 2019). Based on documentation, it supports until 18 Bionic.

**Comment by brushknight** [comment]
Hello! I just saw that you used `fossa` as release name, but we released it under the `focal` release name. http://download.newrelic.com/infrastructure_agent/linux/apt/dists/focal/ and oficial ubuntu code name is `UBUNTU_CODENAME=focal`
You can do `cat /etc/os-release` to verify it. Hope it will solve you issue.
