### ISSUE TITLE
Log Folder and File Permission Denied

### ISSUE THREAD

**Issue by jasonesli** [newrelic/infrastructure-agent-ansible#87]
# Issue
Log Folder and File Not Created During Automated Ansible Installation

## Description
When running the playbook, the infrastructure agent is installed on the target machine however the agent fails to report data to New Relic.

On further investigation, it was noticed that the log folder and log files were not created.

`Sep 19 18:37:04 JE-K8-02 newrelic-infra-service[8530]: time="2020-09-19T18:37:04+08:00" level=info msg="Starting agent process: /usr/bin/newrelic-infra"
Sep 19 18:37:04 JE-K8-02 newrelic-infra-service[8530]: time="2020-09-19T18:37:04+08:00" level=info msg="Creating service..."
Sep 19 18:37:04 JE-K8-02 newrelic-infra-service[8530]: time="2020-09-19T18:37:04+08:00" level=error msg="Can't open log file." action=configureLogRedirection component="New Relic Infrastructure Agent" error="open /var/log/newrelic/nr-infra.log:
Sep 19 18:37:04 JE-K8-02 newrelic-infra-service[8530]: time="2020-09-19T18:37:04+08:00" level=info msg="agent process exited, stopping agent service daemon..." exit_code=1`

Manually creating the file (using touch) and the folder as root resolved the issue and after restarting the newrelic-infra service the Infrastructure Agent began reporting information.

## Expected Behavior
No need to create log file and folder

## Steps to Reproduce
Run Ansible Playbook with **become: yes** flag

![image](https://user-images.githubusercontent.com/71550700/93665616-3f345500-faaa-11ea-8bbb-439c5fa58f74.png)

`ansible-playbook playbook.yml -kK `

-kK flag to enter ssh and become password.

## Your Environment
Debian 10 (Buster) (All Hosts)
Ansible 2.9.13

**Comment by mwhite-ibm** [comment]
I was running into the same issue on Ubuntu.

I noticed `/var/log/newrelic-infra` had been created via the playbook, so changing `log_file` to `/var/log/newrelic-infra/nr-infra.log` fixed it for me.

For context, I was following the example [here](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-ansible).

**Comment by JakubKotkowiak** [comment]
Hello @jasonesli, I've tried to reproduce the issue that occured for you on Debian10 with Ansible: 2.9.13 but it seems that I am unable to do so, everything seems to be working correctly. Could you please tell me if this problem is still occuring?

**Comment by cafferata** [comment]
Hi @JakubKotkowiak, the problem still occurs.

`requirements.yml`

```yaml
- src: newrelic.newrelic-infra
  version: 0.8.2
  name: newrelic.infrastructure-agent
```

`host_vars/all.yml`

```yaml
# newrelic.infrastructure-agent
nrinfragent_config:
  license_key: 'xxx-xxx-xxx-xxx-xxx-xxx'
  log_file: /var/log/newrelic/infrastructure-agent.log
```

`playbooks/newrelic.yml`

```yaml
- hosts: all
  roles:
    - role: newrelic.infrastructure-agent
```

After running the Ansible playbook I (and `newrelic-infra`) expect a directory `/var/log/newrelic/infrastructure-agent.log`. This is not happening.

```bash
systemctl status newrelic-infra -l
```
```
● newrelic-infra.service - New Relic Infrastructure Agent
   Loaded: loaded (/etc/systemd/system/newrelic-infra.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since di 2021-06-29 20:24:25 CEST; 9s ago
  Process: 22345 ExecStart=/usr/bin/newrelic-infra-service (code=exited, status=1/FAILURE)
 Main PID: 22345 (code=exited, status=1/FAILURE)

jun 29 20:24:25 demo-hostname.nl systemd[1]: newrelic-infra.service: main process exited, code=exited, status=1/FAILURE
jun 29 20:24:25 demo-hostname.nl systemd[1]: Unit newrelic-infra.service entered failed state.
jun 29 20:24:25 demo-hostname.nl systemd[1]: newrelic-infra.service failed
```

After (manually) creating this directory, `newrelic-infra` starts up again successfully.

```bash
mkdir /var/log/newrelic/ -p
systemctl restart newrelic-infra
```

```bash
systemctl status newrelic-infra -l
```
```
● newrelic-infra.service - New Relic Infrastructure Agent
   Loaded: loaded (/etc/systemd/system/newrelic-infra.service; enabled; vendor preset: disabled)
   Active: active (running) since di 2021-06-29 20:26:00 CEST; 4s ago
 Main PID: 22629 (newrelic-infra-)
   Memory: 7.5M (limit: 1.0G)
   CGroup: /system.slice/newrelic-infra.service
           ├─22629 /usr/bin/newrelic-infra-service
           └─22634 /usr/bin/newrelic-infra

jun 29 20:26:00 demo-hostname.nl systemd[1]: Stopped New Relic Infrastructure Agent.
jun 29 20:26:00 demo-hostname.nl systemd[1]: Started New Relic Infrastructure Agent.
jun 29 20:26:00 demo-hostname.nl newrelic-infra-service[22629]: time="2021-06-29T20:26:00+02:00" level=info msg="Creating service..."
```

Adding an extra job already solves the problem (*minus the filename*)

```yaml
- name: create log destination directory
  file:
    path: "{{ nrinfragent_config['log_file'] }}"
    state: directory
    recurse: true
```

**Comment by JakubKotkowiak** [comment]
> Hi @JakubKotkowiak, the problem still occurs.
> 
> `requirements.yml`
> 
> ```yaml
> - src: newrelic.newrelic-infra
>   version: 0.8.2
>   name: newrelic.infrastructure-agent
> ```
> 
> `host_vars/all.yml`
> 
> ```yaml
> # newrelic.infrastructure-agent
> nrinfragent_config:
>   license_key: 'xxx-xxx-xxx-xxx-xxx-xxx'
>   log_file: /var/log/newrelic/infrastructure-agent.log
> ```
> 
> `playbooks/newrelic.yml`
> 
> ```yaml
> - hosts: all
>   roles:
>     - role: newrelic.infrastructure-agent
> ```
> 
> After running the Ansible playbook I (and `newrelic-infra`) expect a directory `/var/log/newrelic/infrastructure-agent.log`. This is not happening.
> 
> ```shell
> systemctl status newrelic-infra -l
> ```
> 
> ```
> ● newrelic-infra.service - New Relic Infrastructure Agent
>    Loaded: loaded (/etc/systemd/system/newrelic-infra.service; enabled; vendor preset: disabled)
>    Active: activating (auto-restart) (Result: exit-code) since di 2021-06-29 20:24:25 CEST; 9s ago
>   Process: 22345 ExecStart=/usr/bin/newrelic-infra-service (code=exited, status=1/FAILURE)
>  Main PID: 22345 (code=exited, status=1/FAILURE)
> 
> jun 29 20:24:25 demo-hostname.nl systemd[1]: newrelic-infra.service: main process exited, code=exited, status=1/FAILURE
> jun 29 20:24:25 demo-hostname.nl systemd[1]: Unit newrelic-infra.service entered failed state.
> jun 29 20:24:25 demo-hostname.nl systemd[1]: newrelic-infra.service failed
> ```
> 
> After (manually) creating this directory, `newrelic-infra` starts up again successfully.
> 
> ```shell
> mkdir /var/log/newrelic/ -p
> systemctl restart newrelic-infra
> ```
> 
> ```shell
> systemctl status newrelic-infra -l
> ```
> 
> ```
> ● newrelic-infra.service - New Relic Infrastructure Agent
>    Loaded: loaded (/etc/systemd/system/newrelic-infra.service; enabled; vendor preset: disabled)
>    Active: active (running) since di 2021-06-29 20:26:00 CEST; 4s ago
>  Main PID: 22629 (newrelic-infra-)
>    Memory: 7.5M (limit: 1.0G)
>    CGroup: /system.slice/newrelic-infra.service
>            ├─22629 /usr/bin/newrelic-infra-service
>            └─22634 /usr/bin/newrelic-infra
> 
> jun 29 20:26:00 demo-hostname.nl systemd[1]: Stopped New Relic Infrastructure Agent.
> jun 29 20:26:00 demo-hostname.nl systemd[1]: Started New Relic Infrastructure Agent.
> jun 29 20:26:00 demo-hostname.nl newrelic-infra-service[22629]: time="2021-06-29T20:26:00+02:00" level=info msg="Creating service..."
> ```
> 
> Adding an extra job already solves the problem (_minus the filename_)
> 
> ```yaml
> - name: create log destination directory
>   file:
>     path: "{{ nrinfragent_config['log_file'] }}"
>     state: directory
>     recurse: true
> ```

Okay, I was able to reproduce the issue. I will create a pr with an additional job that ensures the existence of the path. Thanks for providing more information!

**Comment by cafferata** [comment]
Perhaps this comment is superfluous, just in case. See [my code suggestion][1] for the case where `nrinfragent_config['log_file']` is not defined.

[1]: https://github.com/newrelic/infrastructure-agent-ansible/pull/107#discussion_r662575754
