### ISSUE TITLE
Unsupported parameters for (win_service) module: enabled.

### ISSUE THREAD

**Issue by davetapley** [newrelic/infrastructure-agent-ansible#94]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

When trying to install on Windows host you get this error:

```
TASK [newrelic.newrelic-infra : setup agent service] ************************************************************************************************
fatal: [iis_test]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (win_service) module: enabled. Supported parameters include: failure_command, description, update_password, failure_reboot_msg, force_dependent_services, username, display_name, path, start_mode, failure_actions, desktop_interact, load_order_group, required_privileges, name, password, failure_actions_on_non_crash_failure, service_type, pre_shutdown_timeout_ms, sid_info, dependency_action, error_control, state, failure_reset_period_sec, dependencies, pre_shutdown_timeout, failure_reset_period"}
```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

It installs the service ✔️ 

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

Confirmed that [`win_service`](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_service_module.html#parameters) **does not** have an `enabled` parameter.

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

```
  roles:
    - role: newrelic.newrelic-infra
      vars:
        nrinfragent_os_name: Windows
        nrinfragent_os_version: all
```

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

```
ansible-playbook 2.10.8

newrelic.newrelic-infra 0.8.2
```

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

This came in [on original PR](https://github.com/newrelic/infrastructure-agent-ansible/pull/72/files#diff-fddd59af83c2adf8136eeb1c88ad18f4cac9eb5052424a7c8126fc881b6016e0R140). @ripclawffb do you remember if this worked at that time?

**Comment by ripclawffb** [comment]
I'm pretty sure it worked at the time because I was using this role. It looks like someone else tried to fix this issue in PR #81. We just need to merge in the fix. Thanks for your fix as well.

**Comment by ripclawffb** [comment]
I just tested this on Ansible 2.5 and it worked, so maybe it ignored that parameter at the time?

TASK [newrelic.newrelic-infra : setup agent service] ***************************
changed: [192.168.1.88]

PLAY RECAP *********************************************************************
192.168.1.88               : ok=4    changed=1    unreachable=0    failed=0   

Hopefully the PR that fixes this issue gets merged in soon.

**Comment by davetapley** [comment]
Bingo, looks like that check started 'working' (and broke this!) in 2.10 https://github.com/ansible/ansible/pull/64156 ✔️
